export const ADMIN_ROUTES = '/admin'
export const LOGIN_ROUTES = '/login'
export const REGISTRATION_ROUTES = '/registration'
export const MAIL_ROUTES = '/'
export const MESSAGE_ROUTES = '/message'
export const USERPROFILE_ROUTES = '/userprofile'